
CREATE SCHEMA MODELOPROYECTOS;

CREATE TABLE MODELOPROYECTOS.PROYECTOS (
    CODIGO SERIAL,
    NOMBRE VARCHAR(40) NOT NULL,
    HORAS_ESTIMADAS INTEGER,
    HORAS_CONSUMIDAS INTEGER,
    FECHA_ESTIMADA_CIERRE DATE,
    FECHA_CIERRE DATE,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PROYECTOS_PK PRIMARY KEY (CODIGO)
);


CREATE TABLE MODELOPROYECTOS.TAREAS (
    CODIGO SERIAL,
    PROYECTO INTEGER NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    HORAS_ESTIMADAS INTEGER,
    HORAS_REALIZADAS INTEGER,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT TAREAS_PK PRIMARY KEY (CODIGO),
    CONSTRAINT TAREAS_PROYECTOS_FK FOREIGN KEY (PROYECTO) REFERENCES MODELOPROYECTOS.PROYECTOS(CODIGO)
);

CREATE TABLE MODELOPROYECTOS.EMPLEADOS (
    NIF VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDOS VARCHAR(80) NOT NULL,
    CORREO VARCHAR(80) NOT NULL,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT EMPLEADOS_PK PRIMARY KEY (NIF)
);

CREATE TABLE MODELOPROYECTOS.ASIGNACIONES (
    TAREA INTEGER NOT NULL,
    EMPLEADO VARCHAR(9) NOT NULL,
    CONSTRAINT ASIGNACIONES_PK PRIMARY KEY (TAREA, EMPLEADO),
    CONSTRAINT ASIGNACIONES_TAREAS_FK FOREIGN KEY (TAREA) REFERENCES MODELOPROYECTOS.TAREAS(CODIGO),
    CONSTRAINT ASIGNACIONES_EMPLEADOS_FK FOREIGN KEY (EMPLEADO) REFERENCES MODELOPROYECTOS.EMPLEADOS(NIF)
);

CREATE TABLE MODELOPROYECTOS.IMPUTACIONES (
    CODIGO SERIAL,
    EMPLEADO VARCHAR(9) NOT NULL,
    TAREA INTEGER NOT NULL,
    FECHA DATE,
    NUMERO_HORAS INTEGER,
    DESCRIPCION VARCHAR(256),
    CONSTRAINT IMPUTACIONES_PK PRIMARY KEY (CODIGO),
    CONSTRAINT IMPUTACIONES_TAREAS_FK FOREIGN KEY (TAREA) REFERENCES MODELOPROYECTOS.TAREAS(CODIGO),
    CONSTRAINT IMPUTACIONES_EMPLEADOS_FK FOREIGN KEY (EMPLEADO) REFERENCES MODELOPROYECTOS.EMPLEADOS(NIF)    
);
